blog/urls.py
from django.urls import path

from blog.apps import BlogConfig

from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>', ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    # path('activity/<int:pk>', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Article(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    body = models.TextField(verbose_name='Содержимое')
    slug = models.CharField(max_length=200, verbose_name='slug', **NULLABLE)
    preview = models.ImageField(upload_to='article_previews/', **NULLABLE, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    view_count = models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

blog/views.py
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Article


class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'body',)
    extra_context = {
        'title': 'Добавить статью'
    }
    success_url = reverse_lazy('blog:list')

    def get_valid(self, form):
        if form.is_valid():
            new_art = form.save()
            new_art.slug = slugify(new_art.title)
            new_art.save()

            return super().form_valid(form)


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ('title', 'body',)
    extra_context = {
        'title': 'Изменить или редактировать статью'
    }

    def get_valid(self, form):
        if form.is_valid():
            new_art = form.save()
            new_art.slug = slugify(new_art.title)
            new_art.save()

            return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class ArticleListView(ListView):
    model = Article
    extra_context = {
        'title': 'Cтатьи'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class ArticleDetailView(DetailView):
    model = Article
    extra_context = {
        'title': 'Cтатьи'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blog:list')

# def toggle_activity(request, pk):
#     article_item = get_object_or_404(Article, pk=pk)
#     if article_item.is_published:
#         article_item.is_published = False
#     else:
#         article_item.is_published = True
#
#     article_item.save()
#
#     return redirect(reverse('blog:list'))

blog/templates/blog/article_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

                <div class="col-md-4">
                    <div class="card md-4 box-shadow">
                        <div class="card-body">

                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить статью {{ object.title }}?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Статья {{ object.title }} ({{ object.slug }})</h3>
                            </div>
                            <div class="card-body">

                                <table class="table table-striped">
                                    <tr>
                                        <td class="w-25">Статья</td>
                                        <td>{{ object.title }}</td>
                                    </tr>
                                    <tr>
                                        <td class="w-25">slug</td>
                                        <td>{{ object.slug }}</td>
                                    </tr>
                                    <tr>
                                        <td class="w-25">Содержимое:</td>
                                        <td>{{ object.body }}</td>
                                    </tr>
                                    <tr>
                                        <td class="w-25">Публикация:</td>
                                        <td>{{ object.is_published }}</td>
                                    </tr>
                                    <tr>
                                        <td class="w-25">Дата создания</td>
                                        <td>{{ object.created_at }}</td>
                                    </tr>
                                </table>

                           </div>
                            <div class="card-footer">
                                Просмотры: {{ object.view_count }}
                            </div>
                        </div>
                    </div>
                    <div class='col-6'>
                        <img src="/media/{{ object.preview }}"/>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

                <div class="col-md-4">
                    <div class="card md-4 box-shadow">
                        <div class="card-body">

                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                        Сохранить
                                    {% else %}
                                        Создать
                                    {% endif %}
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/article_list.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

                <div class="col-12 md-5">
                    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
                </div>


                {% for object in object_list %}

                    <div class="col-md-4">
                        <div class="card md-4 box-shadow">
                            <div class="card-body">

                                <p class="card-text">
                                    {% if object.is_active %}
                                        {{ object|title }}
                                    {% else %}
                                        <span class="text-muted">{{ object|title }}</span>
                                    {% endif %}

                                </p>

                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'blog:view' object.pk %}" type="button"
                                           class="btn btn-sm btn-outline-secondary">View</a>
                                        <a href="{% url 'blog:edit' object.pk %}" type="button"
                                           class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a href="{% url 'blog:delete' object.pk %}" type="button"
                                           class="btn btn-sm btn-outline-danger">Delete</a>
                                    </div>

                                    {# {% if object.is_active %} #}
                                       {# <a class="btn btn-warning" #}
                                           {# href="{% url 'blog:toggle_activity' object.pk %}">Деактивировать</a> #}
                                    {# {% else %} #}
                                        {# <a class="btn btn-success" #}
                                           {# href="{% url 'blog:toggle_activity' object.pk %}">Активировать</a> #}
                                   {# {% endif %} #}

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}